version: '3'

services:
  client:
    container_name: scoobyfront
    image: leaweibel/scoobyfront
    ports:
      - '3000:3000'
  server:
    container_name: scoobyback
    image: leaweibel/scoobyback
    ports:
      - '5000:5000'
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    ports:
      - '27017:27017'
  




      
